export const CREATE_CHECKIN_REQUEST = 'CRETE_CHECKIN_REQUEST';
export const CREATE_CHECKIN_REQUEST_ERROR = 'CRETE_CHECK_CHECKIN_REQUEST_ERROR';
export const CREATE_CHECKIN_REQUEST_SUCCESS = 'CRETE_CHECKIN_REQUEST_SUCCESS';