export const GET_SUMMARYDATA_REQUEST = "GET_SUMMARYDATA_REQUEST"
export const GET_SUMMARYDATA_REQUEST_SUCCESS = "GET_SUMMARYDATA_REQUEST_SUCCESS"
export const GET_SUMMARYDATA_REQUEST_ERROR = "GET_SUMMARYDATA_LOAD_ERROR"

export const GET_ALL_CUSTOMERS_REQUEST = "GET_ALL_CUSTOMERS_REQUEST"
export const GET_ALL_CUSTOMERS_REQUEST_SUCCESS = "GET_ALL_CUSTOMERS_REQUEST_SUCCESS"
export const GET_ALL_CUSTOMERS_REQUEST_ERROR = "GET_ALL_CUSTOMERS_REQUEST_ERROR"

export const GET_CUSTOMER_REQUEST = "GET_CUSTOMER_REQUEST"
export const GET_CUSTOMER_REQUEST_SUCCESS = "GET_CUSTOMER_REQUEST_SUCCESS"
export const GET_CUSTOMER_REQUEST_ERROR = "GET_CUSTOMER_REQUEST_ERROR"