export const GET_CONNECTIONS_REQUEST = 'GET_CONNECTIONS_REQUEST';
export const GET_CONNECTIONS_REQUEST_SUCCESS = 'GET_CONNECTIONS_REQUEST_SUCCESS';
export const GET_CONNECTIONS_REQUEST_FAIL = 'GET_CONNECTIONS_REQUEST_FAIL';